### ISSUE TITLE
Remove global CSS rules

### ISSUE THREAD

**Issue by Novitoll** [jtrussell/angular-snap.js#105]
Things in CSS like below are not desired as they break user's custom HTML and body.

```css
html, body {
  font-family: sans-serif;
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
}
```
